### ISSUE TITLE
[Feature Reqeust]

### ISSUE THREAD

**Issue by LeonBoettcher** [GRX005/PlaytimeLink#1]
Playeholders for

Individual Playtime:
%VPTlink_player_toptimeplace% - which shows the Playe in the Toplist of the player  

also add to the description of the plugin on Hangar, SpigotMC and so on...
Where you have to install the Playtimelink on your velocity eg. every server or only the proxy would be helpfull

**Comment by GRX005** [comment]
Feature added in the latest update, updated the description on hangar and modrinth if that's what you meant.
