### ISSUE TITLE
[BUG] Sometimes after a server restart, (for all users?) the placeholder will be stuck on "loading..."

### ISSUE THREAD

**Issue by berrydiaboli** [GRX005/PlaytimeLink#3]
[NOTE] If there was a way to get debug enabled I can give the error, but I checked the config and there isn't

[Theory] I believe its due to players trying to join before the server is fully online, but that's my guess

**Comment by GRX005** [comment]
Well I can't really reproduce the issue like this, you should give more specifics.

**Comment by berrydiaboli** [comment]
basically while the server is starting, still loading plugins and stuff, I believe when attempting to join while its loading

I have no idea how to really replicate it, but I do have the placeholder on scoreboard and on a hologram on the world, do you think that could be the issue?

**Comment by berrydiaboli** [comment]
![image](https://github.com/user-attachments/assets/a7ca553c-4a09-4c53-8ad1-b9d3d64d699c)

I encountered it again and it just sticks with "loading..."

**Comment by GRX005** [comment]
Hi, this should be fixed in the latest update.

**Comment by berrydiaboli** [comment]
Thanks! I will do testing on this, and if you don't hear from me again, then assume it is fixed!
